### ISSUE TITLE
Field appearing out of order in tabs

### ISSUE THREAD

**Issue by ryanmasuga** [vaersaagod/matrixmate#12] opened 2019-10-17 18:00 UTC
We have types with tabs that won't display the fields in the order we want them. 

Relevant part of the Config:
```
'text' => [
    'tabs' => [
        [
        'label' => 'Content',
        'fields' => ['alignment','textField','ctaButton'],
        ],
    ],
```
On this one, the "alignment" field is always displaying at the bottom of the Matrix block, but we want that to display first, and the CTA Button last. Other tabs in this type are displaying in correct order.

![image](https://user-images.githubusercontent.com/988995/67034038-f67b5b80-f0e4-11e9-9b39-fa4cc5b7a9cd.png)

Here's another type whose first tab is not ordering correctly:
```
'textImageBlock' => [
  'tabs' => [
      [
      'label' => 'Content',
      'fields' => ['contentOrder','images','caption','textField', 'ctaButton'],
      ]
  ],
],
```

This type is _really_ off, displaying in this order:
textField, contentOrder, ctaButton, images, caption

![image](https://user-images.githubusercontent.com/988995/67034452-b7013f00-f0e5-11e9-8dfa-d1d635f57e88.png)

This is not happening for all types. I can't seem to determine a rhyme or reason for it, like only happening on blocks with 3 or more tabs, or something like that. I can switch the order of the items in the config and it seems to have no effect. Is the config malformed, maybe? Any thoughts?

--
Craft 3.1.34.3 
Matrix Mate: 1.2.2

**Comment by mmikkel** [comment] 2019-10-17 18:34
MatrixMate doesn't actually change the order of the block type's fields when you arrange them into tabs – if the `alignment` field sits below the `textField` in the block type's field layout, it's going to appear below it in a tab, no matter what order you use for the `'fields'` in the MatrixMate config.

In other words, I don't think there's a bug here – you're probably just seeing the fields render as per their chronological order in the block type's field layout.

**Comment by mmikkel** [comment] 2019-10-17 18:51
To be clear though, the current behaviour is a deliberate design choice. We could definitely add a config setting (that works similarly to the [`defaultTabName`](https://github.com/vaersaagod/matrixmate#defaulttabname-stringbool) setting, i.e. being possible to set both on a per-field and per-type basis) called `useTabFieldOrder` or something, that would make MatrixMate use the field order from the config instead of the block type's field layout, if set to `true`.

**Comment by ryanmasuga** [comment] 2019-10-17 20:47
Thanks for the clarification. I updated field order in the Matrix block settings and those changes were reflected correctly on the entries in the CP. So - correct, not a bug, but it would be a nice enhancement to be able to override that with a config variable!

**Comment by mmikkel** [comment] 2021-11-09 07:53
Closing this. The current behaviour is by design and upon reflection I'm not really interested in adding a `useTabFieldOrder` setting.

**Closed by mmikkel** 2021-11-09 07:53 UTC
Labels: enhancement
